"""Create client table

Revision ID: 12bd57dccdcd
Revises: c565ce128d3a
Create Date: 2021-05-24 22:50:34.072785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12bd57dccdcd'
down_revision = 'c565ce128d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False, comment='Фамилия'),
    sa.Column('last_name', sa.String(length=64), nullable=False, comment='Имя'),
    sa.Column('middle_name', sa.String(length=64), nullable=True, comment='Отчество'),
    sa.Column('birth_date', sa.Date(), nullable=False, comment='Дата рождения'),
    sa.Column('gender', sa.String(length=3), nullable=True, comment='Пол'),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='Телефон'),
    sa.Column('email', sa.String(length=20), nullable=True, comment='Адрес электронной почты'),
    sa.Column('privilege', sa.String(length=1), nullable=True, comment='Наличие льгот'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
