"""Create price ticket table

Revision ID: 9974dd92aaf5
Revises: 12bd57dccdcd
Create Date: 2021-05-24 22:52:35.932691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9974dd92aaf5'
down_revision = '12bd57dccdcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_ticket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.SmallInteger(), nullable=True, comment='Цена в будний день'),
    sa.Column('price_weekend', sa.SmallInteger(), nullable=True, comment='Цена выходного дня'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание позиции'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'client', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_table('price_ticket')
    # ### end Alembic commands ###
